site_name: Twitter Requirements

nav:
    - Pŕe-rastreabilidade:
      - RichPicture: pre-rastreabilidade/richpicture.md
    - Elicitação:
      - Entrevistas: elicitacao/entrevistas/entrevistas.md
      - Storytelling: elicitacao/storytelling.md
      - Requisitos & MoSCoW: elicitacao/requisitos.md

repo_url: https://github.com/Requisitos2-2019/Twitter/

docs_dir: twitter_docs/
site_dir: docs/

theme: yeti
