site_name: Twitter Requirements

nav:
    - Home: index.md
    - Pŕe-rastreabilidade:
      - RichPicture: pre-rastreabilidade/richpicture.md

repo_url: https://github.com/Requisitos2-2019/Twitter/

docs_dir: twitter_docs/
site_dir: docs/

theme: yeti
