site_name: Twitter Requirements

nav:
    - Pŕe-rastreabilidade:
      - RichPicture: pre-rastreabilidade/richpicture.md
    - Elicitação:
      - Entrevistas: elicitacao/entrevistas/entrevistas.md
      - Storytelling: elicitacao/storytelling.md
      - Requisitos & MoSCoW: elicitacao/requisitos.md
    - Modelagem:
      - Cenários: modelagem/cenarios/cenarios.md
      - Léxicos: modelagem/lexicos/lexicos.md
      - Casos de uso: modelagem/user_cases.md
      - Caso de uso Trending Topics: modelagem/use_cases_specifications/trending_topics.md
    - Outros artefatos:
      - 5W2H: outros_artefatos/5w2h.md
      - SWOT: outros_artefatos/swot.md

repo_url: https://github.com/Requisitos2-2019/Twitter/

docs_dir: twitter_docs/
site_dir: docs/

theme: yeti
