site_name: Twitter Requirements

nav:
    - Home: index.md
    - Pŕe-rastreabilidade:
      - RichPicture: pre-rastreabilidade/richpicture.md
    - Elicitação:
      - Entrevistas: elicitacao/entrevistas/entrevistas.md
      - Requisitos: elicitacao/requisitos.md
    - Outros artefatos:
      - 5W2H: outros_artefatos/5w2h.md

repo_url: https://github.com/Requisitos2-2019/Twitter/

docs_dir: twitter_docs/
site_dir: docs/

theme: yeti
