site_name: Twitter Requirements

nav:
    - Pŕe-rastreabilidade:
      - RichPicture: pre-rastreabilidade/richpicture.md
    - Elicitação:
      - Entrevistas: elicitacao/entrevistas/entrevistas.md
      - Storytelling: elicitacao/storytelling.md
      - Requisitos & MoSCoW: elicitacao/requisitos.md
    - Modelagem:
      - Cenários 1.0: modelagem/cenarios/cenarios-1_0.md
      - Cenários 0.1: modelagem/cenarios/cenarios.md
      - Léxicos 1.0: modelagem/lexicos/lexicos-1_0.md
      - Léxicos 0.1: modelagem/lexicos/lexicos.md
      - NFR Segurança: modelagem/NFR/nfr-seguranca.md
      - Caso de uso - Geral: modelagem/use_cases_specifications/user_case_geral.md
      - Caso de uso - Trending Topics: modelagem/use_cases_specifications/trending_topics.md
      - Caso de uso - Login: modelagem/use_cases_specifications/login.md
    - Outros artefatos:
      - PDCA: outros_artefatos/PDCA.md
      - 5W2H: outros_artefatos/5w2h.md
      - SWOT: outros_artefatos/swot.md

repo_url: https://github.com/Requisitos2-2019/Twitter/

docs_dir: twitter_docs/
site_dir: docs/

theme: yeti
